---
- hosts: all
  tasks:
  - name: clone git repository
    git:
      repo: https://gitlab.com/CarlosQuixada/normatizador.git
      dest: /home/trustv/normatizador
      version: "{{ version }}"
  - name: build docker image
    shell: cd normatizador && docker build -t trustvox/normatizador:{{ version }} .
  - name: register possibly running container with same name
    shell: docker ps -a | grep normatizador | wc -l
    register: normatizador_running_container
  - name: stop possibly running container with same name
    shell: docker rm -f normatizador
    when: normatizador_running_container.stdout != "0"
  - name: run container
    shell: >
      docker run -e "normatizador_ENV=production" -d
      --name normatizador
      -p 9935:8000
      trustvox/normatizador:{{ version }}
  - name: remove cloned git repo
    file:
      path: /home/trustv/normatizador
      state: absent
