---
- hosts: all
  tasks:
  - name: clone git repository
    git:
      repo: https://gitlab.com/trustvox/rambo
      dest: /home/trustv/rambo
      version: "{{ version }}"
  - name: build docker image
    shell: cd rambo && docker build -t trustvox/rambo:{{ version }} .
  - name: register possibly running container with same name
    shell: docker ps -a | grep rambo | wc -l
    register: rambo_running_container
  - name: stop possibly running container with same name
    shell: docker rm -f rambo
    when: rambo_running_container.stdout != "0"
  - name: run container
    shell: >
      docker run -e "RAMBO_ENV=production" -d
      --name rambo
      -p 9901:8000
      trustvox/rambo:{{ version }}
  - name: remove cloned git repo
    file:
      path: /home/trustv/rambo
      state: absent
